import type { CodegenConfig } from '@graphql-codegen/cli';
 
const config: CodegenConfig = {
  schema: './src/graphql/schema.gql',
  generates: {
    './src/types.ts': {
      config: {
        useIndexSignature: true,
      },
      plugins: [
        { add: {
          content: '/* This code is generated by GraphQL Codegen. Do not edit manually. */\n',
        } },
        'typescript'
      ],
    },
  },
};
export default config;
